import Sidebar from "@/components/shared/Sidebar";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession(authOptions);

  // ✅ যদি ইউজার লগিন না করে থাকে, তাহলে /login এ রিডিরেক্ট করো
  if (!session) {
    redirect("/login");
  }

  return (
    <div className="min-h-screen my-2">
      <div className="flex justify-between">
        <div className="w-[20%]">
          <Sidebar />
        </div>
        <div className="w-[80%] bg-slate-100 rounded-xl ml-2">
          {children}
        </div>
      </div>
    </div>
  );
}
